# Generated by Django 4.2.5 on 2023-09-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Names', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('DNI', models.PositiveIntegerField()),
                ('Phone', models.PositiveIntegerField()),
            ],
        ),
    ]
