# Generated by Django 4.2.5 on 2023-09-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='DNI',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Phone',
            field=models.CharField(max_length=9),
        ),
    ]
