# Generated by Django 4.2.5 on 2023-09-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_lead_dni_alter_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='DNI',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Phone',
            field=models.PositiveIntegerField(),
        ),
    ]
